#!/usr/bin/perl -w
#
# Automatically generate a configuration file for uprocfs.
#
# With the auto-generated configuration file, uproc creates a PID namespace for
# each UID and GID defined in the system.
#
# All namespaces are represented inside uprocfs in the following form:
#
#   uid.<username>
#   gid.<groupname>
#
# Where:
#    - <username> is the name of the user as reported in /etc/passwd
#    - <groupname> is the name of the group as reported in /etc/group
#
# The configuration file is printed to standard output.
#
# Copyright (C) 2011 Andrea Righi <andrea@betterlinux.com>

use strict;

my ($name, $uid, $gid);

print << "EOF";
# /etc/uproc.conf
#
# This configuration file has been automatically generated by $0
#
# Each line describes the rule to create a PID namespace inside uprocfs.
#
# Each rule is defined in the form:
#
#   <type> <key> <name>
#
# Where:
#
#   <type> can be:
#          - uid: select all tasks of a certain UID
#          - gid: select all tasks of a certain GID
#
#   <key> is:
#          - the UID number if <type> is "uid"
#          - the GID number if <type> is "gid"
#
#   <name> is the name of the namespace
EOF

print "\n### UIDs ###\n";
while (($name, $_, $uid, $gid, $_, $_, $_, $_, $_) = getpwent()) {
	print "uid $uid uid.$name\n";
}
print "\n### GIDs ###\n";
while (($name, $_, $gid, $_) = getgrent()) {
	print "gid $gid gid.$name\n";
}
